archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
      darwin: macOS
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip

build:
  binary: nsq_to_dogstatsd
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  main: nsq_to_dogstatsd.go

dockers:
 - image_templates:
    - "ruimarinho/nsq-dogstatsd:latest"
    - "ruimarinho/nsq-dogstatsd:{{ .Tag }}"
