name: Build and push Docker images

on: [push]

jobs:
  build:
    name: Build and push image to Docker Hub
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      repository: ruimarinho/nsq-dogstatsd
      tag_with_ref: true
      push: ${{ startsWith(github.ref, 'refs/tags/') }}
